### ISSUE TITLE
Hosting behind Traefik under a path prefix

### ISSUE THREAD

**Issue by jpmeijers** [lipanski/docker-static-website#2]
I have a docker-compose config similar to this:

```
  invoices:
    image: lipanski/docker-static-website:latest
    volumes:
      - "/root/generate-invoices:/home/static"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoices.rule=(Host(`my-host.com`) && PathPrefix(`/invoices/`))"
      - "traefik.http.middlewares.strip-invoices.stripprefix.prefixes=/invoices"
      - "traefik.http.routers.invoices.middlewares=strip-invoices@docker"
      - "traefik.http.routers.invoices.entrypoints=websecure"
      - "traefik.http.routers.invoices.tls.certresolver=myresolver"
```

This allows my to go to https://my-host.com/invoices to see the file list served by docker-static-website. An issue with this is however that the hyperlinks in the file list are absolute and not relative to the path. A file named "fileA" will link to https://my-host.com/fileA rather than to https://my-host.com/invoices/fileA.

Looking at the config options for thttpd there isn't an option to make these links relative of specify a base path.

A workaround I found was to mount my volume under a subdirectory matching the base path I want. Ex:
```
  invoices:
    image: lipanski/docker-static-website:latest
    volumes:
      - "/root/generate-invoices:/home/static/invoices"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoices.rule=(Host(`my-host.com`) && PathPrefix(`/invoices/`))"
      - "traefik.http.routers.invoices.entrypoints=websecure"
      - "traefik.http.routers.invoices.tls.certresolver=myresolver"
```
