### ISSUE TITLE
docker-compose.yml and httpd.conf directory configs

### ISSUE THREAD

**Issue by janekska** [lipanski/docker-static-website#31]
Hi,
I successfully managed to install latest container on openmediavault.
First tests opened my test index.html file.

But I stuck at some problems:

1st - default yml config file creates httpd.conf as directories:
```
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/busyboxhttpd/data:/home/static
      - ./httpd.conf:/home/static/httpd.conf:ro
```
Than I could not create httpd.conf file as there is a directory with the same name.
This I solved by removing or commenting out last line and than I can add httpd.conf file and successfully test that changes in configs give expected results.

Except the 2nd problem - could not get links to subdirectories open - got 404, even when using these configs:
`H:/home/static`
or no H config that means . or root dir.
and
`I:index.html`

Where could be the problem?

brgds

**Comment by gunjubas** [comment]
can you please provide full compose.yaml?

**Comment by janekska** [comment]
> can you please provide full compose.yaml?

```
---
services:
  webserver:
    image: lipanski/docker-static-website:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/busyboxhttpd/data:/home/static
#      - ./httpd.conf:/home/static/httpd.conf:ro
```
