### ISSUE TITLE
[suggest] add a sample default page

### ISSUE THREAD

**Issue by shishirong** [lipanski/docker-static-website#32]
similar nginx default page , for  tip user that it is work well.

**Comment by jenstroeger** [comment]
I second this suggestion, because with a simple page available this container could be used as a final container in a Compose file of health checks, for example
```yaml
services:
  postgres:
    ...
    healthcheck:
      test: pg_isready
  rabbitmq:
    ...
    healthcheck:
      test: rabbitmq-diagnostics --quiet ping
  redis:
    ...
    healthcheck:
      test: redis-cli ping | grep PONG

wait-for-all-services:
  image: lipanski/docker-static-website:latest
  depends_on:
    postgres:
      condition: service_healthy
    rabbitmq:
      condition: service_healthy
    redis:
      condition: service_healthy
```
Then the container can be polled and if it responds with 200 the other services should also be healthy.
